-include .env

build:; forge build # make build esegue il comando forge build quindi carica lo smart contract sulla chain 

deploy:; forge script scipt/FundMe.s.sol --rpc-url htttp://127.0.0.1:8545 --broadcast --private-key 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC

test:; forge test 

testCoverage:; forge coverage