-include .env

build:; forge build # make build esegue il comando forge build quindi carica lo smart contract sulla chain 

deploy:; forge script script/FundMe.s.sol --rpc-url http://127.0.0.1:8545 --broadcast --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

test:; forge test 

testCoverage:; forge coverage